### ISSUE TITLE
Unsupported operand types: string + int

### ISSUE THREAD

**Issue by bfjare** [wrav/oembed#76] opened 2021-06-10 16:36 UTC
<img width="1174" alt="Screen Shot 2021-06-10 at 10 37 19 AM" src="https://user-images.githubusercontent.com/11744681/121563639-d6925d00-c9d7-11eb-9750-4712712dce2a.png">

Getting this error when enabling cache in the control panel.

**Comment by reganlawton** [comment] 2021-06-15 06:03
@bfjare Are you able to try the v1.3.7 update and if that doesn't help can you give me so more troubleshooting.

Did it work once you disabled cache and then enable it again after testing the URL / page?
Did you have a URL I might be able to test?
Do you have the GraphQL query I might be able to test?

**Comment by michaelhue** [comment] 2021-06-15 11:56
I've been running into this as well after updating to PHP 8. I'm on the plugin's latest version `1.3.8`.
The problem is line 135 in `OembedService`:

```php
Craft::$app->cache->set($cacheKey, $media, 'P1H');
```

The third parameter should be an integer, as per `CacheInterface`:

> @param int $duration default duration in seconds before the cache will expire. If not set,
   default [[defaultDuration]] value is used.

This is triggering an error in PHP8 since adding strings and integers is not supported anymore.

**Comment by bfjare** [comment] 2021-06-15 15:39
Confirming if I downgrade the server to PHP 7.4 the error goes away.

**Comment by reganlawton** [comment] 2021-06-16 00:09
Argh so its a PHP 8 issue I'll have to look into

**Comment by michaelhue** [comment] 2021-06-16 08:26
Well, yes and no. The underlying problem is the wrong usage of `Craft::$app->cache->set()`. The third argument is expected to be a duration in seconds after which the cache will expire. You are passing a duration period designator `P1H` instead. 

You can see the problem in @bfjares first screenshot, the line highlighted in red. The duration (in your case a string) is added to the current `time()` (a unix timestamp as integer), which is not allowed in PHP 8 anymore because it can have unexpected results.

The solution is the correct usage of `Craft::$app->cache->set()` with a duration integer as the third argument.

**Comment by bfjare** [comment] 2021-06-16 15:35
@michaelhue thanks for the help good sir!

**Comment by RyanRoberts** [comment] 2021-07-08 19:11
Would love a fix for this, unfortunatly I doubt I can help.

**Comment by gglnx** [comment] 2021-07-20 20:01
I have fixed this too in my pull request #84.

**Closed** 2021-07-21 01:22 UTC
