### ISSUE TITLE
GraphQL error: String cannot represent value

### ISSUE THREAD

**Issue by joshuabaker** [wrav/oembed#74] opened 2021-04-20 15:00 UTC
After updating, I’m consistently getting an error with any embed: “String cannot represent value”

```json
{
  "message": "String cannot represent value: {\"url\":\"https:\\/\\/www.youtube.com\\/watch?v=z9Ug-3qhrwY\",\"oembed\":null}",
  "extensions": {
    "category": "graphql"
  }
}
```

Using Craft 3.6.12.

@reganlawton Do you have any idea what might be causing that?

**Comment by reganlawton** [comment] 2021-04-21 11:59
I'll have to troubleshoot this in the morning but that's very weird did you tell and empty the field and renter that field?

**Comment by joshuabaker** [comment] 2021-04-21 12:04
Thank you! 🙏🏻 

I’ve tried creating a new block too with the same result. I’ll share any further context if I find anything.

**Comment by denisyilmaz** [comment] 2021-05-21 06:18
I have the same issue. I tried reentering the videos to a new block (inside NEO) and it then worked again for one site, but when switching to the other site the error appears again. 

```bash
2021-05-21 08:16:14 [-][-][-][error][GraphQL\Error\Error] String cannot represent value: {"url":"https:\/\/vimeo.com\/546404759","oembed":null}
2021-05-21 08:16:14 [-][-][-][info][application] $_GET = [
    'p' => 'api'
]
```

**Comment by joshuabaker** [comment] 2021-05-25 10:51
So the GraphQL error here suggests that the JSON isn’t getting decoded somehow. I’ve witnessed JSON data getting doubly encoded before in Craft and wonder if that might be what’s happening here (i.e. after decoding the JSON, it’s actually still a string).

@denisyilmaz Do you still have an example where this *doesn’t* work? If so, you might try putting `Json::decodeIfJson` call after [this line](https://github.com/wrav/oembed/blob/d011aa7e9f823e54f37e16a90d2545a92896368f/src/fields/OembedField.php#L114) locally to see if that fixes it.

**Comment by denisyilmaz** [comment] 2021-05-27 12:36
yes, for example this project has this error currently live: https://www.basics.berlin/de/styling/artists/julius-forgo/projekt/bmw-vision-i-next

when switchtig to english (top right) the same query with different lang param is send to the server (but there the translated oembed field returns the error above).

The error is reproducable:
1. add a new neo block with the oembed field in it
2. add a vimeo link
3. save entry
4. open entry in one language: oembed field works 
5. open same entry in other language: oembed field fails

The language where the field is first saved in and the language first called in the frontend must not be the same to get it to work the same time. It seems a GraphQL Cache is filled with the value which then is decoded a second time when the other language is called. can that be?

**Comment by denisyilmaz** [comment] 2021-05-27 12:54
@joshuabaker i modified the line as you suggested but it still did not work:

```php
if (is_string($value) && $decValue = Json::decodeIfJson($value, true)) {
    if (isset($decValue['url'])) {
        return new OembedModel($decValue['url']);
    }
}
```

**Comment by denisyilmaz** [comment] 2021-05-27 13:10
acutally, i tried differend options. this one worked once for both languages, but only if applied after the entry was saved and before the query was called the first time:

```php
if (is_string($value) && $decValue = Json::decodeIfJson($value, true)) {
    if (isset($decValue['url'])) {
        if(Json::isJsonObject($decValue['url'])) {
            $decValue = Json::decodeIfJson($decValue['url']);
        }
        return new OembedModel($decValue['url']);
    }
}
```
Otherswise the backend fails on save with error, which is the expected behavior:
```bash
Argument 1 passed to craft\helpers\Json::isJsonObject() must be of the type string, array given, called in /home/runcloud/webapps/msb-craft-cms/vendor/wrav/oembed/src/fields/OembedField.php on line 117
```
so it seems somewhere in this the value of `$decValue['url']` gets saved back to the server.

because when I test to return only the `$decValue` (not the url field) i get following error:
```json
[
  {
    "message": "String cannot represent value: {\"url\":{\"url\":\"https:\\/\\/vimeo.com\\/210599507\",\"oembed\":null},\"oembed\":null}",
    "extensions": {
      "category": "graphql"
    }
  }
]
```
so it seems `new OembedModel()` is called multiple times at some point.

**Comment by joshuabaker** [comment] 2021-05-27 15:44
@denisyilmaz That’s a good find. I’m seeing the same nested object in the `url` attribute on another site.

![image](https://user-images.githubusercontent.com/160484/119856067-574a5700-bf0a-11eb-8895-24b05ba0063a.png)

**Comment by devinpitcher** [comment] 2021-05-27 17:37
To add some additional data, I am running into this as well. 

The error is thrown when using a YouTube URL in this format:
`https://youtu.be/9wfbEC_es94`

Updating to the format below did **not** throw the error:
`https://youtube.com/watch?v=9wfbEC_es94`

**Comment by joshuabaker** [comment] 2021-05-27 17:40
@devinpitcher That sounds unrelated, to be honest. Are you finding that consistently with short YouTube URLs? Might be worth opening a separate issue.

**Comment by devinpitcher** [comment] 2021-05-27 17:44
> @devinpitcher That sounds unrelated, to be honest. Are you finding that consistently with short YouTube URLs? Might be worth opening a separate issue.

Yeah, I added four entries with short URLs, and one with a regular URL, and all the short URLs errored out but the standard URL was fine.

**Comment by devinpitcher** [comment] 2021-05-27 18:19
I get the previews, but I get the error when attempting to query via GraphQL.

**Comment by andrewhawkes** [comment] 2021-06-04 13:12
I'm currently returning `code` on the field in a GraphQL query but it's no longer returning for new Vimeo videos.
Could this be related?

**Comment by andrewhawkes** [comment] 2021-06-06 15:05
I've had a bit of a dip into the DB and seeing how the field data is saved. It looks like something has changed recently which is causing the data to be saved in a different way:

**Working**

```{"url":"https://vimeo.com/492107391","oembed":null}```

**Not working**
```{"url":{"url":{"url":"https://vimeo.com/528336142","oembed":null},"oembed":null},"oembed":null}```

**Comment by reganlawton** [comment] 2021-06-06 22:39
Yeah there seems to be a legacy issue thats changing it to to repeat itself inside itself. This why have been an issue from Craft 1 or 2 days BUT I think @joshuabaker your PR #75 fixes this?

**Comment by reganlawton** [comment] 2021-06-15 04:16
I'll update this with the looping that @denisyilmaz considered

**Comment by reganlawton** [comment] 2021-06-15 06:04
I tagged v1.3.7 with  some testing vectors that I could think up and if you are able to change I'll get it a couple of days till I close this issue.

**Closed** 2022-05-26 07:36 UTC
